version: '2'

services:
    docker-symfony_db:
        image: mysql
        container_name: ${PROJECT_NAME}_db
        volumes:
            - "./docker/container/.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    docker-symfony_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}_phpmyadmin
        environment:
            PMA_HOST: ${PROJECT_NAME}_db
        ports:
            - "8080:80"
        links:
            - docker-symfony_db

    docker-symfony_php:
        build:
            context: ./docker/build/php-fpm
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                PHP_VERSION: ${PHP_VERSION}
                PROJECT_USER: ${PROJECT_USER}
                TIMEZONE: ${TIMEZONE}
        image: ${PROJECT_NAME}_php
        container_name: ${PROJECT_NAME}_php
        environment:
            SYMFONY_ENV: ${SYMFONY_ENV}
            SSH_AUTH_SOCK: /tmp/agent.sock
        volumes:
            - ${APP_PATH}:/var/www/${PROJECT_NAME}
            - $SSH_AUTH_SOCK:/tmp/agent.sock
            - ~/.bash_history:/root/.bash_history

    docker-symfony_nginx:
        build:
            context: ./docker/build/nginx
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                PROJECT_PROTOCOL: ${PROJECT_PROTOCOL}
        image: ${PROJECT_NAME}_nginx
        container_name: ${PROJECT_NAME}_nginx
        ports:
            - 80:80
            - 443:443
        volumes_from:
            - docker-symfony_php
        volumes:
            - ./docker/container/logs/nginx/:/var/log/nginx