#!/usr/bin/env bash

TO-DO
# source "`dirname \"$0\"`/read-env-config"

# docker-compose exec "${PROJECT_NAME}_php" bash -c "php bin/console doctrine:database:create --if-not-exists"
# docker-compose exec "${PROJECT_NAME}_php" bash -c "php bin/console doctrine:migrations:version --add --all -n"

# source "`dirname \"$0\"`/docker-permissions"