#!/usr/bin/env bash

# Get current file directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Get project's root
PARENTDIR="$(dirname "$DIR")"

# Export ENV variables
export $(cat $PARENTDIR/.env | grep -v ^# | xargs)